version: '3'

volumes:
  mongo-data:

networks:
  vidiot-net:
    driver: bridge

services:

  lb:
    build: 
      dockerfile: ./Dockerfile
      context: .
    depends_on:
      - "db"
    ports:
      - "5000:5000"
      - "1935:1935"
      - "8080:8080"
      - "8086:8086"
    restart: on-failure
    env_file: 
      - ./scripts/docker_env.env
    networks: 
      - vidiot-net
    volumes: 
      - ./:/vidiot/
    command: sh -c "tail -F lb"
    logging:
         driver: "json-file"
         options:
             max-file: "5"
             max-size: "100m"

  db:
    image: mongo
    volumes:
      - mongo-data:/var/lib/mongodb/
      - ./scripts/mongo_setup.sh:/docker-entrypoint-initdb.d/init.sh
    env_file: 
      - ./scripts/docker_env.env
    expose:
      - "27017"
    networks: 
      - vidiot-net
    logging:
         driver: "json-file"
         options:
             max-file: "5"
             max-size: "100m"
